#version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: slim-backend
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./backend/php.ini:/usr/local/etc/php/php.ini
    environment:
      - PHP_ENV=development
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./slimappfront
      dockerfile: ../frontend/Dockerfile
      target: development
    container_name: slim-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./slimappfront:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_BASE_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

    # MySQL Database
  database:
    image: mysql:8.0
    container_name: slim-db
    command: --default-authentication-plugin=mysql_native_password --disable-log-bin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${DB_NAME:-slim_app}
      - MYSQL_USER=${DB_USER:-slim_user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-slim_password}
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Optional: Add a reverse proxy (nginx) to serve both frontend and backend
  nginx:
    image: nginx:alpine
    container_name: app-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge
